In [ ]:
#TASK 1
"""Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”
3, 45, 83,21, Have a go at ‘w’ ‘r’ ‘a’ """
my_file = open("numbers.txt", "r")
print(my_file.read())


In [ ]:
input1 = int(input("Please enter your 1st number"))
input2 = int(input("Please enter your 2nd number"))
input3 = int(input("Please enter your 3rd number"))
input4 = int(input("Please enter your 4th number"))
string_to_write_to_file = str(input1) + " " + str(input2) + " " + str(input3) + " " + str(input4)
print(string_to_write_to_file)
my_file = open("numbers.txt", "w")
my_file.write(string_to_write_to_file)
f.close()

In [ ]:
# Reading
with open("numbers.txt", "r") as myfile:
    data = myfile.read().replace('\n', ',')

myfile.close()

print(data)

In [ ]:
#TASK 2
"""Write a program to ask a student for their percentage mark and convert this to a grade.
The conversion will be done in a function called mark_grade"""
percentage_of_marks = int(input("Please enter your percentage of marks"))
print(percentage_of_marks)

if percentage_of_marks >= 81 and percentage_of_marks <=100:
    print("GRADE A")
elif percentage_of_marks >= 61 and percentage_of_marks <=80:
    print("GRADE B")
elif percentage_of_marks >=41 and percentage_of_marks <=60:
    print("GRADE C")
elif percentage_of_marks >=0 and percentage_of_marks <=40:
    print("YOU HAVE FAILED")

In [ ]:
def ReturnTheGrade(percentage_of_marks):
    
    if percentage_of_marks >= 81 and percentage_of_marks <=100:
        return "GRADE A"
    elif percentage_of_marks >= 61 and percentage_of_marks <=80:
        return "GRADE B"
    elif percentage_of_marks >=41 and percentage_of_marks <=60:
        return "GRADE C"
    elif percentage_of_marks >=0 and percentage_of_marks <=40:
        return "YOU HAVE FAILED"
    

percentage_of_marks = int(input("Please enter your percentage of marks"))
print(ReturnTheGrade(percentage_of_marks))


In [5]:
#1. Create a 1D array of numbers from 0 to 9
import numpy as np 
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
#2. Create a 3×3 NumPy array of all Boolean value Trues

import numpy as np

array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
newarr = array2.astype(bool)
print (array2)
print (newarr)
print (newarr.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
bool


In [24]:
# 3.Extract all odd numbers from array of 1 to 10
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
filter_arr = arr % 2 == 1
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False  True False  True False  True False  True False]
[1 3 5 7 9]


In [ ]:
# 4.Replace all odd numbers in an array of 1 10 with the value 1

In [34]:
#5.Convert a 1D array to a 2D array with 2 rows
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [35]:
#6.Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to #calculate totals
import numpy as np

arra = np.array([10, 11, 12, 13, 14, 15])
arrb = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arra, arrb)
newarr1 = np.dot(arra, arrb)

print(newarr)
print(newarr1)

[30 32 34 36 38 40]
1705
